[XTrain, YTrain] = digitTrain4DArrayData;
[XTest, YTest] = digitTest4DArrayData;

addpath('../src'); % Tells MATLAB where to find buildLayers.m
layers = buildLayers();

options = trainingOptions('adam', ...
    'InitialLearnRate',0.001, ...
    'MaxEpochs',5, ...
    'MiniBatchSize',64, ...
    'Shuffle','every-epoch', ...
    'ValidationData',{XTest, YTest}, ...
    'ValidationFrequency',30, ...
    'Verbose',false, ...
    'Plots','training-progress');

net = trainNetwork(XTrain, YTrain, layers, options);
if ~exist('../models','dir'), mkdir ../models; end
save('../models/trainedNet.mat', 'net');